### ISSUE TITLE
Engine integration

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#19]
@1ozturkbe i've gotten the engine integrated everywhere except in the cruise breguet range and steady level flight constraints.

Is anything in the aircraft sized for cruise? I can't think of anything but don't know much about the fuselage.

**Comment by 1ozturkbe** [comment]
No, it isn't sized for anything in cruise. The fuselage only has a set of max load cases, and its only performance parameters have to do with drag.

**Comment by 1ozturkbe** [comment]
Are you asking this because the engine is still creating issues?

**Comment by mayork** [comment]
yep. last night i was able to integrate the engine into everything except the breguet range and steady level flight constraints. I'm not entirely sure what the issue is when I integrate with those since they're the same constraints I use in the engine/flight profile/simple aircraft model.

**Comment by 1ozturkbe** [comment]
Interesting... The only reason I'd see any reason for worry is the fact that T_e (engine out thrust) is sized by the climb-out thrust of the engines. But that seems to work fine. Perhaps it could have been with the use of Nsplit? You've probably checked this already though. 
Another issue might have to do with whether or not cruise-climb is allowed? I'm just spitballing here.

**Comment by mayork** [comment]
I don't think it's Nsplit, i've printed the constraint out and the vector indexes appear correct. 

I considered cruise-climb, but don't see a reason this formulation shouldn't work since it already has elsewhere. I plan on looking into this more.

**Comment by mayork** [comment]
i think that the horizontal tail volume is going to zero

**Comment by 1ozturkbe** [comment]
Why would it do that, when it was perfectly fine without the engine?

**Comment by mayork** [comment]
can't say for sure. this is certainly adding an extra degree of freedom. Right now the most I can say is that there appears to be a relation between what I set the min allowed HT volume coeff to and the min allowed cruise thrust. Working on getting more detail now.

**Comment by 1ozturkbe** [comment]
Btw also, why did you change the basic engine model in D8_integration? We need it to run CFP.

**Comment by mayork** [comment]
oh whoops...didn't realize you were still running CFP. You can uncomment the lines and i'll make an untracked file.

I edited the file because the comment out parts are integrated to the real engine model.

**Comment by mayork** [comment]
the last push converges. cruise thrust limited to 37000 N and tail volume limited to 0.05. What are your thoughts on removing the HT and seeing if everything else integrates then adding the HT back in? I think this could all go back to that min static margin constraint

**Comment by 1ozturkbe** [comment]
(Btw I'm assuming you lower-bounded both the thrust and the volume coefficient here). I don't think that is necessary or useful at this point. The horizontal tail behaves as expected in CFP, and removing it would just revert us to having subs for CG and AC, which really dumbs down the aircraft superclass. I think the approach should be to incrementally unbound the troublesome variables instead. I also think it is worth doing some sweeps on the integrated model, because it doesn't make too much sense that the HT breaks with the engine, but does fine without it. I think the failure is more nuanced than that, and we need to figure out when exactly the model breaks.

**Comment by mayork** [comment]
alright, but i don't know how to integrate the engine fully without removing the tail. I'm not sure what engine-tail interaction is causing the issue, and the only way I can think of is to remove the tail, integrate the engine, and then piece by piece add in the tail. Do you have another idea on how to do this?

**Comment by 1ozturkbe** [comment]
Well firstly, I had changed the cmw value to 0.1 in the old model, but it has reverted to 1 in engine_integration. That is why the HT is so small.

**Comment by 1ozturkbe** [comment]
With that new value, the HT should be just fine.

**Comment by 1ozturkbe** [comment]
And, other than the vertical tail span constraint (greater than 4*engine radius), there is no constraint that explicitly links the engine to the tail. Therefore, I suggest running a sweep of the cruise thrust until the model fails, and then trying to decipher what is going on by plotting the data. I do not think the model is failing because there is a non-sensical constraint. Also, isn't a cruise thrust of 37000N per engine really high? Perhaps we can't generate enough drag :P You may try to relax the drag constraint to thrust >= drag.

**Comment by 1ozturkbe** [comment]
I can run a series of engine parameter sweeps with the working CFP, and see if it makes a difference. Btw, you may also want to check the substitutions within D8_engine_integration and see if they match CFP. I have tried to be diligent about moving all of the subs into the dictionary at the end of the document, but there are a few in Aircraft and AircraftP because of the duplicate variable name issues.

**Comment by 1ozturkbe** [comment]
Also, I have been doing through TASOPT again to make sure that there were not glaring sizing constraints that were missing... immediately found two issues that seem quite important. One is the fact that engine and apu weights significantly affect bending moment. The other is that the aircraft has positive buoyancy weight at altitude. Will fix and push on CFP; should not affect the model results drastically.

**Comment by mayork** [comment]
doest tasopt account for the positive buoyancy weight?

**Comment by 1ozturkbe** [comment]
Yes it does. I will dig up in the runfiles to see what default cabin pressure TASOPT uses.

**Comment by 1ozturkbe** [comment]
I want your opinion on something. It seems tricky to integrate the buoyancy weight into the W_start - W_end scheme in Mission. Do you have any objection to adding it as such:
```python
W_avg >= (W_start + W_end + W_buoy)**0.5
```
It might be cleaner, since then we don't have to turn a bunch of monomial equalities in Mission into posynomial inequalities, and we know that the difference in W_start and W_end is only a function of fuel burn, and not also altitude change. Lmk what you think.

**Comment by mayork** [comment]
For it to be a valid constraint the + would have to be * and I'm not sure 
```
W_avg >= (W_start * W_end * W_buoy)**
```

makes sense. The way it's written W_buoy should be a negative value, correct?

**Comment by 1ozturkbe** [comment]
I updated... Sorry about the hasty, typo filled message lol.

**Comment by mayork** [comment]
no worries, i think my comments still stand

**Comment by 1ozturkbe** [comment]
No, the following would be a terrible approximation:
```python
W_avg >= (W_start * W_end * W_buoy)**.33
```
Since W_buoy is a totally different order of magnitude, the approx. would be waaay off. You'd have to add it at the end.

**Comment by mayork** [comment]
sure but 

```python
W_avg >= (W_start + W_end + W_buoy)**0.5
```
isn't a valid constraint. You can't have variables added together and then raise to a power

**Comment by 1ozturkbe** [comment]
I told you it was a typo...

**Comment by mayork** [comment]
oh sorry...the message didn't' update on my screen

**Comment by mayork** [comment]
```python
W_avg >= ((W_start + W_buoy) * (W_end + W_buoy))**.5
```
is also not valid

**Comment by 1ozturkbe** [comment]
I mean this one: 
```python
W_avg >= (W_start * W_end)**0.5 +  W_buoy
```
Doing this over chat is hard.

**Comment by mayork** [comment]
okay that makes sense. the only thing i don't get now is the sign on W_buoy...shouldn't the buoyant force be acting in the direction of lift and thereby decreasing the average weight

**Comment by 1ozturkbe** [comment]
No. The air is denser on the inside, therefore you have an inverted helium balloon :P

**Comment by 1ozturkbe** [comment]
Upon first glance, haven't found any significant differences between CFP and D8_engine integration. Though I am confused about one thing. You include engine within both cruise and climbP, but not in aircraftP, unlike the other performance models. Why is that? Could that be the reason for the error?

**Comment by mayork** [comment]
it's just due to the architecture of the engine model, it was a conscious decision

**Comment by 1ozturkbe** [comment]
Cool; best of luck with the reintegration, and let me know if I can help you with anything. Let's definitely meet tomorrow to discuss.

**Comment by mayork** [comment]
the problem appears to not be the state linking

**Comment by 1ozturkbe** [comment]
Btw, of course the cruise altitude of the aircraft is going to be constant! Because we had CruiseAlt as a variable, it is necessarily true that both cruise segments happen at the same altitude.

**Comment by mayork** [comment]
i adjusted that in the one where cruise climb is allowed

**Comment by 1ozturkbe** [comment]
K cool, I thought I had had a eureka moment :P

**Comment by 1ozturkbe** [comment]
For some reason, I can't resolve the discrepancy of between the 'thrust' of oldengine and 'F' of engine during climb... Just can't set them equal. Any ideas? It doesn't look like 'thrust' has any subs or constraints other than the 2*max cruise thrust constraint.

**Comment by mayork** [comment]
that's the issue i've been battling. Not sure what the problem is.

**Comment by 1ozturkbe** [comment]
Well it seems pretty critical. I will beat my head against it for a bit.

**Comment by 1ozturkbe** [comment]
I have found the solution to our problems. We just need to get rid of oldengine altogether. Just have some placeholder variables instead. Some seriously weird shit is going on with oldengine that makes zero sense. Will do this now.

**Comment by mayork** [comment]
let me know if it works

**Comment by 1ozturkbe** [comment]
This is the most vexing issue I have ever seen... still not working.

**Comment by mayork** [comment]
I've almost got the HT integrated ithink

**Comment by mayork** [comment]
engine is now integrated, closing
