### ISSUE TITLE
Use TASOPT tail drag model or the fits

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#56]
So I was able to dig up the drag model TASOPT uses...it assumes a drag coefficient then weights it by Stail/Swing. The question is, do we use this or the fits? The fits give us higher drag values (I'd argue more accurate). Normally I'd say use the TASOPT method but I think that makes us less accurate cause then our fuel burn is more directly impacted by variations in tail and wing sizing...Thoughts? We can also run both and demonstrate the differences

**Comment by 1ozturkbe** [comment]
Whaaat? Seems super rudimentary... I'm surprised there isn't something more advanced in TASOPT. I would prefer using the fits; we don't have to follow the TASOPT models verbatim, and I think it is sketchy to say that we can just put a fudge factor on the tail drag. It's ok if we are a little high on fuel burn because our tail model is better. Let me know what you think. @whoburg do you want to weigh in here?

**Comment by whoburg** [comment]
I'd say use the constant drag coefficient if the goal is TASOPT validation, but a model that captures Re and thickness variation would be more appropriate long term. If using fit's it will be important to make sure we're fitting a reasonable choice of airfoil family for tails.

**Comment by 1ozturkbe** [comment]
@mayork I guess then we can size the tails using the drag coefficients provided, as well as the set aspect ratios so we can get as close to TASOPT as possible.

**Comment by mayork** [comment]
using TASOPT tail drag for now, closing
